name: Notify Slack & Release Version

on:
  push:
    branches:
      - main
      - test
      - develop
  pull_request:
    types: [opened, closed]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

jobs:
  slackNotificationOnPr:
    name: Slack Notification
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Send slack message on leave-app-frontend on pr
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
                "text": "PR: ${{ github.event.pull_request.title}} by ${{ github.event.pull_request.user.login}}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": ":sparkles: *Incoming PR* :sparkles: \n *By:* <${{ github.event.pull_request.user.html_url}}|${{ github.event.pull_request.user.login}}> \n *Link:* <${{ github.event.pull_request.html_url}}|${{ github.event.pull_request.title}}> | *Commit:* <${{ github.event.pull_request.head.repo.html_url}}/commit/${{ github.event.pull_request.head.sha}}|${{ github.event.pull_request.head.sha}}>"
                    }
                  } 
                ] 
              }

  slackNotificationOnMerge:
    name: Slack Notification on merge
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
    steps:
      - name: Send slack notification on merge
        id: slackNotificationOnMerge
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "PR merged: ${{ github.event.pull_request.title}}",
              "blocks": [
                {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": ":rocket: *Merged*\n* By:* <${{ github.event.pull_request.user.html_url}}|${{ github.event.pull_request.merged_by.login}}>\n*Link:* <${{ github.event.pull_request.html_url}}|${{ github.event.pull_request.title}}>"
                    }
                  } 
                
                ]
              }

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: npm install

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_TOKEN }}
        run: npx semantic-release
