name: PR and Push Events

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
  push:
    branches:
      - main
      - develop
      - test

jobs:
  process_events:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: PR Opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: echo "New PR Created"

      - name: PR Closed
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: echo "PR merged"

      - name: PR Synchronize
        if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
        run: echo "A push was made"

      - name: Push to Branch
        if: github.event_name == 'push'
        run: echo "A push was made"
